<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>IpScopePro</AssemblyName>
    <RootNamespace>IpScopePro</RootNamespace>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Authors>IpScope</Authors>
    <Description>Network monitoring and scanning tool for Windows</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\app.ico" />
    <EmbeddedResource Include="Resources\oui.csv" />
    <EmbeddedResource Include="Resources\mam.csv" />
    <EmbeddedResource Include="Resources\oui36.csv" />
  </ItemGroup>

</Project>
