using System.ComponentModel;
using IpScopePro.Models;

namespace IpScopePro.Services;

public class LocalizationService : INotifyPropertyChanged
{
    public static LocalizationService Instance { get; } = new();

    private AppLanguage _language = AppLanguage.Spanish;

    public AppLanguage Language
    {
        get => _language;
        set
        {
            if (_language == value) return;
            _language = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(string.Empty));
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
            LanguageChanged?.Invoke(value);
        }
    }

    public event Action<AppLanguage>? LanguageChanged;
    public event PropertyChangedEventHandler? PropertyChanged;

    public string this[string key] => Get(key);

    public string Get(string key)
    {
        if (_language == AppLanguage.English)
            return English.TryGetValue(key, out var en) ? en : key;
        return Spanish.TryGetValue(key, out var es) ? es : key;
    }

    public string TranslateStatus(ProbeStatus status) => status switch
    {
        ProbeStatus.Up => Get("StatusUp"),
        ProbeStatus.Down => Get("StatusDown"),
        ProbeStatus.Error => Get("StatusError"),
        ProbeStatus.LatencyHigh => Get("StatusLatencyHigh"),
        ProbeStatus.LatencyNormal => Get("StatusUp"),
        ProbeStatus.Indeterminate => Get("StatusIndeterminate"),
        ProbeStatus.Inactive => Get("StatusInactive"),
        _ => status.ToString()
    };

    private static readonly Dictionary<string, string> English = new()
    {
        ["ToggleTheme"] = "Toggle theme",
        ["LightTheme"] = "Light",
        ["DarkTheme"] = "Dark",
        ["Minimize"] = "Minimize",
        ["Maximize"] = "Maximize",
        ["Close"] = "Close",
        ["Hide"] = "Hide",

        ["NavProbe"] = "Probe",
        ["NavScanner"] = "Scanner",
        ["NavSettings"] = "Settings",
        ["AddProbe"] = "+ Add",
        ["AddProbeTip"] = "Add new probe",
        ["StartAll"] = "▶ Start All",
        ["StartAllTip"] = "Start all probes",
        ["StopAll"] = "■ Stop All",
        ["StopAllTip"] = "Stop all probes",
        ["RemoveAll"] = "🗑 Remove All",
        ["RemoveAllTip"] = "Remove all probes",
        ["Scroll"] = "Scroll",
        ["Fixed"] = "Fixed",
        ["Batch"] = "✎ Batch",
        ["BatchTip"] = "Batch input addresses",
        ["Import"] = "Import",
        ["Export"] = "Export",
        ["RemoveAllConfirm"] = "Remove all {0} probes?",
        ["RemoveAllTitle"] = "Remove All Probes",
        ["WindowTitleProbes"] = "IpScope Pro - Probes",

        ["NoProbes"] = "No probes yet",
        ["AddToStart"] = "Click + Add to start monitoring",
        ["CrowdedFixed"] = "Fixed view is too crowded.",
        ["SwitchToScrollHint"] = "Switch to scroll mode to properly see all probes.",
        ["SwitchToScroll"] = "↕ Switch to Scroll",

        ["MaximizeProbe"] = "Maximize probe",
        ["RestoreProbe"] = "Restore probe",
        ["Remove"] = "Remove",
        ["RemoveProbe"] = "Remove probe",
        ["Start"] = "▶ START",
        ["Stop"] = "■ STOP",
        ["StartTip"] = "Start",
        ["StopTip"] = "Stop",
        ["Restore"] = "Restore",

        ["StatusUp"] = "UP",
        ["StatusDown"] = "DOWN",
        ["StatusError"] = "ERROR",
        ["StatusLatencyHigh"] = "HIGH LATENCY",
        ["StatusIndeterminate"] = "?",
        ["StatusInactive"] = "STOPPED",
        ["StatusChangedBody"] = "Status changed from {0} to {1} at {2}",
        ["StatsSummary"] = "Sent: {0} | Recv: {1} | Lost: {2} ({3:F1}%) | Avg: {4:F1}ms",

        ["IpRange"] = "IP Range",
        ["IpRangeTip"] = "Single IP: 192.168.1.10\nRange: 192.168.1.1-254\nCIDR: 192.168.1.0/24\nComma-separated list",
        ["Ports"] = "Ports",
        ["ScanModeFast"] = "Fast",
        ["ScanModeExhaustive"] = "Exhaustive",
        ["ScanModeTip"] = "Fast: scans ports only on hosts that reply to ping.\nExhaustive: scans ports on every host, even if it does not reply to ping.",
        ["Scan"] = "▶ Scan",
        ["StopScan"] = "■ Stop",
        ["PortsToScan"] = "Ports to scan",
        ["PortsToScanTip"] = "Single ports and ranges separated by commas.\nExample: 1-1024, 5000-5015, 24565",
        ["ShowAliveOnly"] = "Show only active hosts",
        ["ColStatus"] = "Status",
        ["ColIp"] = "IP",
        ["ColHostname"] = "Hostname",
        ["ColMac"] = "MAC",
        ["ColVendor"] = "Vendor",
        ["ColPorts"] = "Ports",
        ["ColMacAddress"] = "MAC Address",
        ["ColOpenPorts"] = "Open Ports",
        ["AddToProbes"] = "▶ Add to Probes",
        ["SelectPortsTitle"] = "Select ports to monitor",
        ["SelectPortsHeader"] = "⛶  Select ports to monitor",
        ["SelectPortsHint"] = "Choose which checks to add as monitors:",
        ["PingMonitor"] = "Ping (ICMP)",
        ["SelectAllPorts"] = "Select all",
        ["ClearPorts"] = "Clear all",
        ["StatusReady"] = "Ready",
        ["StatusScanning"] = "Scanning...",
        ["StatusExpanding"] = "Expanding IP ranges...",
        ["StatusNoIps"] = "No valid IPs found",
        ["StatusNoPorts"] = "No valid ports specified",
        ["ScanComplete"] = "Scan complete. {0} alive out of {1} scanned.",
        ["ScanError"] = "Scan error: {0}",
        ["ScanCancelled"] = "Scan cancelled",
        ["NetworkScanner"] = "Network Scanner",

        ["SettingsTitle"] = "IpScope Pro Settings",
        ["SettingsHeader"] = "⚙  Settings",
        ["ScanResults"] = "Scan Results",
        ["TabGeneral"] = "General",
        ["TabPing"] = "Ping",
        ["TabNotifications"] = "Notifications",
        ["TabColors"] = "Colors",
        ["TabStartup"] = "Startup",
        ["LanguageGroup"] = "Language",
        ["Timing"] = "Timing",
        ["PingInterval"] = "Ping Interval (ms)",
        ["PingTimeout"] = "Ping Timeout (ms)",
        ["FailedPingsDown"] = "Failed Pings → Down",
        ["HighLatency"] = "High Latency (ms)",
        ["ConcurrentPings"] = "Concurrent Pings",
        ["WindowsGroup"] = "Windows",
        ["EnableNotifications"] = "Enable Notifications",
        ["WindowsToast"] = "Windows Toast Notifications",
        ["CooldownSec"] = "Alert cooldown (sec)",
        ["EmailSmtp"] = "Email / SMTP",
        ["EnableEmail"] = "Enable Email Alerts",
        ["SmtpServer"] = "SMTP Server",
        ["SmtpPort"] = "SMTP Port",
        ["SmtpUser"] = "SMTP User",
        ["SmtpUserTip"] = "The SMTP username. Some providers use an API key or token here instead of an email address (e.g. Cloudflare, Amazon SES, SendGrid).",
        ["Password"] = "Password",
        ["EmailFrom"] = "From",
        ["EmailFromTip"] = "The sender address shown to recipients. Use an address your SMTP provider allows (e.g. a verified address on your domain).",
        ["To"] = "To",
        ["ToTip"] = "Separate multiple recipients with commas.\nExample: one@mail.com, two@mail.com",
        ["SendTestEmail"] = "Send Test Email",
        ["Telegram"] = "Telegram",
        ["EnableTelegram"] = "Enable Telegram",
        ["BotToken"] = "Bot Token",
        ["ChatId"] = "Chat ID",
        ["SendTestTelegram"] = "Send Test to Telegram",
        ["Audio"] = "Audio",
        ["EnableAudio"] = "Enable Audio Alerts (loss only)",
        ["SoundFile"] = "Sound File",
        ["DarkThemeGroup"] = "Dark Theme",
        ["LightThemeGroup"] = "Light Theme",
        ["Up"] = "Up",
        ["Down"] = "Down",
        ["Error"] = "Error",
        ["Latency"] = "Latency",
        ["Indeterm"] = "Indeterm.",
        ["Inactive"] = "Inactive",
        ["IpText"] = "IP Text",
        ["Apply"] = "Apply",
        ["RestoreDefaults"] = "Restore Defaults",
        ["ApplicationGroup"] = "Application",
        ["MinimizeToTray"] = "Minimize to System Tray",
        ["StartWithWindows"] = "Start with Windows",
        ["LogToFile"] = "Log to File",
        ["LogDirectory"] = "Log Directory",
        ["LoggingGroup"] = "Logging",
        ["InstallGroup"] = "Installation",
        ["InstallHint"] = "Install IpScope Pro on this PC to keep your settings between sessions and enable 'Start with Windows'. Until then, the app runs in portable mode and saves nothing.",
        ["InstallApp"] = "Install on Windows",
        ["UninstallApp"] = "Uninstall",
        ["InstallSuccess"] = "IpScope Pro has been installed. The application will now restart from the installed location.",
        ["InstallFailed"] = "Install failed:\n{0}",
        ["UninstallSuccess"] = "IpScope Pro has been uninstalled.",
        ["UninstallFailed"] = "Uninstall failed:\n{0}",
        ["UninstallConfirm"] = "The program files and shortcuts will be removed.\n\nDo you also want to delete the saved settings and monitors?\n\n[Yes] Delete everything\n[No] Keep my data\n[Cancel] Cancel",
        ["UninstallTitle"] = "Uninstall IpScope Pro",
        ["UninstallWarning"] = "This will remove IpScope Pro from this computer.",
        ["UninstallSummary"] = "The program files and shortcuts will be deleted.",
        ["UninstallDataQuestion"] = "What do you want to do with your saved data?",
        ["UninstallKeepData"] = "Keep my settings and monitors",
        ["UninstallKeepDataHint"] = "Your settings and monitors will remain on this computer in case you reinstall.",
        ["UninstallDeleteData"] = "Delete settings and monitors",
        ["UninstallDeleteDataHint"] = "This will permanently erase all your settings, monitors and saved data.",
        ["UninstallAction"] = "Uninstall",
        ["InstallTitle"] = "Install IpScope Pro",
        ["InstallLocation"] = "Install Location",
        ["Browse"] = "Browse...",
        ["ShortcutsGroup"] = "Shortcuts",
        ["DesktopShortcut"] = "Create a desktop shortcut",
        ["StartMenuShortcut"] = "Create a Start Menu shortcut",
        ["InstallPathRequired"] = "Please choose an installation directory.",
        ["InstallAdminRequired"] = "Installing to this location requires administrator permissions. Restart the installation with administrator rights?",
        ["InstallHintAdmin"] = "Installing to Program Files requires administrator permissions.",
        ["Open"] = "Open",
        ["Exit"] = "Exit",
        ["ExportSettings"] = "Export Settings",
        ["ImportSettings"] = "Import Settings",
        ["Cancel"] = "Cancel",
        ["Save"] = "Save",

        ["EnterEncryptionPassword"] = "Enter encryption password:",
        ["EnterDecryptionPassword"] = "Enter decryption password:",
        ["ExportFailed"] = "Export failed.",
        ["ErrorTitle"] = "Error",
        ["InvalidFile"] = "Invalid file or wrong password.",
        ["ImportSuccess"] = "Settings imported successfully.",
        ["ImportTitle"] = "Import",
        ["ImportFailed"] = "Import failed. Check password.",
        ["FillEmailFields"] = "Please fill in all email fields (server, port, user, password, from, to).",
        ["TestEmailTitle"] = "Test Email",
        ["TestEmailSent"] = "Test email sent successfully!",
        ["TestEmailFailed"] = "Failed to send test email:\n{0}",
        ["FillTelegram"] = "Please fill in both Bot Token and Chat ID.",
        ["TestTelegramTitle"] = "Test Telegram",
        ["TestTelegramSent"] = "Test message sent to Telegram successfully!",
        ["TestTelegramFailed"] = "Failed to send Telegram test message:\n{0}",
        ["BatchInputTitle"] = "Batch Input",
        ["BatchInputHeader"] = "✎  Batch Input",
        ["EnterHosts"] = "Enter hostnames or IPs (one per line):",
        ["FormatHint"] = "Format: hostname or IP:port (e.g. 192.168.1.1:80)",
        ["AddAll"] = "Add All",
        ["PasswordTitle"] = "Password",
        ["Ok"] = "OK",
        ["AlertsHeader"] = "⬟ Alerts",
        ["AlertsWindowTitle"] = "IpScope Alerts",

        ["EmailTimestamp"] = "Timestamp",
        ["TestEmailSubject"] = "[IpScope Pro] Test Email",
        ["TestEmailBody"] = "This is a test email from IpScope Pro.\nIf you received this, your email notification settings are configured correctly.",
        ["TestTelegramMessage"] = "This is a test message from IpScope Pro.\nIf you received this, your Telegram notification settings are configured correctly."
    };

    private static readonly Dictionary<string, string> Spanish = new()
    {
        ["ToggleTheme"] = "Cambiar tema",
        ["LightTheme"] = "Claro",
        ["DarkTheme"] = "Oscuro",
        ["Minimize"] = "Minimizar",
        ["Maximize"] = "Maximizar",
        ["Close"] = "Cerrar",
        ["Hide"] = "Ocultar",

        ["NavProbe"] = "Monitor",
        ["NavScanner"] = "Escáner",
        ["NavSettings"] = "Ajustes",
        ["AddProbe"] = "+ Añadir",
        ["AddProbeTip"] = "Añadir nuevo monitor",
        ["StartAll"] = "▶ Iniciar todo",
        ["StartAllTip"] = "Iniciar todos los monitores",
        ["StopAll"] = "■ Detener todo",
        ["StopAllTip"] = "Detener todos los monitores",
        ["RemoveAll"] = "🗑 Eliminar todo",
        ["RemoveAllTip"] = "Eliminar todos los monitores",
        ["Scroll"] = "Desplazamiento",
        ["Fixed"] = "Fijo",
        ["Batch"] = "✎ Lote",
        ["BatchTip"] = "Entrada de direcciones por lote",
        ["Import"] = "Importar",
        ["Export"] = "Exportar",
        ["RemoveAllConfirm"] = "¿Eliminar los {0} monitores?",
        ["RemoveAllTitle"] = "Eliminar todos los monitores",
        ["WindowTitleProbes"] = "IpScope Pro - Monitores",

        ["NoProbes"] = "Aún no hay monitores",
        ["AddToStart"] = "Haz clic en + Añadir para empezar a monitorizar",
        ["CrowdedFixed"] = "La vista fija está demasiado llena.",
        ["SwitchToScrollHint"] = "Cambia al modo desplazamiento para ver todos los monitores correctamente.",
        ["SwitchToScroll"] = "↕ Cambiar a desplazamiento",

        ["MaximizeProbe"] = "Maximizar monitor",
        ["RestoreProbe"] = "Restaurar monitor",
        ["Remove"] = "Quitar",
        ["RemoveProbe"] = "Quitar monitor",
        ["Start"] = "▶ INICIAR",
        ["Stop"] = "■ DETENER",
        ["StartTip"] = "Iniciar",
        ["StopTip"] = "Detener",
        ["Restore"] = "Restaurar",

        ["StatusUp"] = "ACTIVO",
        ["StatusDown"] = "CAÍDO",
        ["StatusError"] = "ERROR",
        ["StatusLatencyHigh"] = "LATENCIA ALTA",
        ["StatusIndeterminate"] = "?",
        ["StatusInactive"] = "DETENIDO",
        ["StatusChangedBody"] = "Estado cambiado de {0} a {1} a las {2}",
        ["StatsSummary"] = "Env: {0} | Rec: {1} | Perd: {2} ({3:F1}%) | Prom: {4:F1}ms",

        ["IpRange"] = "Rango de IP",
        ["IpRangeTip"] = "IP única: 192.168.1.10\nRango: 192.168.1.1-254\nCIDR: 192.168.1.0/24\nLista separada por comas",
        ["Ports"] = "Puertos",
        ["ScanModeFast"] = "Rápido",
        ["ScanModeExhaustive"] = "Exhaustivo",
        ["ScanModeTip"] = "Rápido: escanea puertos solo en hosts que responden al ping.\nExhaustivo: escanea puertos en todos los hosts, aunque no respondan al ping.",
        ["Scan"] = "▶ Escanear",
        ["StopScan"] = "■ Detener",
        ["PortsToScan"] = "Puertos a escanear",
        ["PortsToScanTip"] = "Puertos individuales y rangos separados por comas.\nEjemplo: 1-1024, 5000-5015, 24565",
        ["ShowAliveOnly"] = "Mostrar solo hosts activos",
        ["ColStatus"] = "Estado",
        ["ColIp"] = "IP",
        ["ColHostname"] = "Nombre de host",
        ["ColMac"] = "MAC",
        ["ColVendor"] = "Fabricante",
        ["ColPorts"] = "Puertos",
        ["ColMacAddress"] = "Dirección MAC",
        ["ColOpenPorts"] = "Puertos abiertos",
        ["AddToProbes"] = "▶ Añadir a monitores",
        ["SelectPortsTitle"] = "Seleccionar puertos a monitorizar",
        ["SelectPortsHeader"] = "⛶  Seleccionar puertos a monitorizar",
        ["SelectPortsHint"] = "Elige qué comprobaciones añadir como monitores:",
        ["PingMonitor"] = "Ping (ICMP)",
        ["SelectAllPorts"] = "Seleccionar todo",
        ["ClearPorts"] = "Limpiar todo",
        ["StatusReady"] = "Listo",
        ["StatusScanning"] = "Escaneando...",
        ["StatusExpanding"] = "Ampliando rangos de IP...",
        ["StatusNoIps"] = "No se encontraron IPs válidas",
        ["StatusNoPorts"] = "No se especificaron puertos válidos",
        ["ScanComplete"] = "Escaneo completado. {0} activos de {1} escaneados.",
        ["ScanError"] = "Error de escaneo: {0}",
        ["ScanCancelled"] = "Escaneo cancelado",
        ["NetworkScanner"] = "Escáner de red",

        ["SettingsTitle"] = "Ajustes de IpScope Pro",
        ["SettingsHeader"] = "⚙  Ajustes",
        ["ScanResults"] = "Resultados del escaneo",
        ["TabGeneral"] = "General",
        ["TabPing"] = "Ping",
        ["TabNotifications"] = "Notificaciones",
        ["TabColors"] = "Colores",
        ["TabStartup"] = "Inicio",
        ["LanguageGroup"] = "Idioma",
        ["Timing"] = "Temporización",
        ["PingInterval"] = "Intervalo de ping (ms)",
        ["PingTimeout"] = "Tiempo de espera de ping (ms)",
        ["FailedPingsDown"] = "Pings fallidos → Caído",
        ["HighLatency"] = "Latencia alta (ms)",
        ["ConcurrentPings"] = "Pings simultáneos",
        ["WindowsGroup"] = "Windows",
        ["EnableNotifications"] = "Activar notificaciones",
        ["WindowsToast"] = "Notificaciones emergentes de Windows",
        ["CooldownSec"] = "Enfriamiento de alerta (seg)",
        ["EmailSmtp"] = "Correo / SMTP",
        ["EnableEmail"] = "Activar alertas por correo",
        ["SmtpServer"] = "Servidor SMTP",
        ["SmtpPort"] = "Puerto SMTP",
        ["SmtpUser"] = "Usuario SMTP",
        ["SmtpUserTip"] = "El usuario SMTP. Algunos proveedores usan aquí una clave API o un token en lugar de un correo (p. ej. Cloudflare, Amazon SES, SendGrid).",
        ["Password"] = "Contraseña",
        ["EmailFrom"] = "De (From)",
        ["EmailFromTip"] = "La dirección de correo que verá el destinatario. Usa una dirección que permita tu proveedor SMTP (p. ej. una dirección verificada de tu dominio).",
        ["To"] = "Para",
        ["ToTip"] = "Separa varios destinatarios con comas.\nEjemplo: uno@correo.com, dos@correo.com",
        ["SendTestEmail"] = "Enviar correo de prueba",
        ["Telegram"] = "Telegram",
        ["EnableTelegram"] = "Activar Telegram",
        ["BotToken"] = "Token del bot",
        ["ChatId"] = "ID de chat",
        ["SendTestTelegram"] = "Enviar prueba a Telegram",
        ["Audio"] = "Audio",
        ["EnableAudio"] = "Activar alertas de audio (solo caídas)",
        ["SoundFile"] = "Archivo de sonido",
        ["DarkThemeGroup"] = "Tema oscuro",
        ["LightThemeGroup"] = "Tema claro",
        ["Up"] = "Activo",
        ["Down"] = "Caído",
        ["Error"] = "Error",
        ["Latency"] = "Latencia",
        ["Indeterm"] = "Indet.",
        ["Inactive"] = "Inactivo",
        ["IpText"] = "Texto IP",
        ["Apply"] = "Aplicar",
        ["RestoreDefaults"] = "Restaurar valores",
        ["ApplicationGroup"] = "Aplicación",
        ["MinimizeToTray"] = "Minimizar a la bandeja del sistema",
        ["StartWithWindows"] = "Iniciar con Windows",
        ["LogToFile"] = "Registrar en archivo",
        ["LogDirectory"] = "Directorio de registros",
        ["LoggingGroup"] = "Registro",
        ["InstallGroup"] = "Instalación",
        ["InstallHint"] = "Instala IpScope Pro en este equipo para conservar los ajustes entre sesiones y activar 'Iniciar con Windows'. Hasta entonces la aplicación funciona en modo portable y no guarda nada.",
        ["InstallApp"] = "Instalar en Windows",
        ["UninstallApp"] = "Desinstalar",
        ["InstallSuccess"] = "IpScope Pro se ha instalado. La aplicación se reiniciará desde la ubicación instalada.",
        ["InstallFailed"] = "Error al instalar:\n{0}",
        ["UninstallSuccess"] = "IpScope Pro se ha desinstalado.",
        ["UninstallFailed"] = "Error al desinstalar:\n{0}",
        ["UninstallConfirm"] = "Se eliminarán los archivos del programa y los accesos directos.\n\n¿Quieres eliminar también los ajustes y monitores guardados?\n\n[Sí] Eliminar todo\n[No] Conservar mis datos\n[Cancelar] Cancelar",
        ["UninstallTitle"] = "Desinstalar IpScope Pro",
        ["UninstallWarning"] = "Esto eliminará IpScope Pro de este equipo.",
        ["UninstallSummary"] = "Se eliminarán los archivos del programa y los accesos directos.",
        ["UninstallDataQuestion"] = "¿Qué quieres hacer con tus datos guardados?",
        ["UninstallKeepData"] = "Conservar mis ajustes y monitores",
        ["UninstallKeepDataHint"] = "Tus ajustes y monitores permanecerán en este equipo por si vuelves a instalar.",
        ["UninstallDeleteData"] = "Eliminar ajustes y monitores",
        ["UninstallDeleteDataHint"] = "Se borrarán permanentemente todos tus ajustes, monitores y datos guardados.",
        ["UninstallAction"] = "Desinstalar",
        ["InstallTitle"] = "Instalar IpScope Pro",
        ["InstallLocation"] = "Ubicación de instalación",
        ["Browse"] = "Examinar...",
        ["ShortcutsGroup"] = "Accesos directos",
        ["DesktopShortcut"] = "Crear un acceso directo en el escritorio",
        ["StartMenuShortcut"] = "Crear un acceso directo en el menú Inicio",
        ["InstallPathRequired"] = "Elige una carpeta de instalación.",
        ["InstallAdminRequired"] = "La instalación en esta ubicación requiere permisos de administrador. ¿Reiniciar la instalación con permisos de administrador?",
        ["InstallHintAdmin"] = "La instalación en Archivos de programa requiere permisos de administrador.",
        ["Open"] = "Abrir",
        ["Exit"] = "Salir",
        ["ExportSettings"] = "Exportar ajustes",
        ["ImportSettings"] = "Importar ajustes",
        ["Cancel"] = "Cancelar",
        ["Save"] = "Guardar",

        ["EnterEncryptionPassword"] = "Introduce la contraseña de cifrado:",
        ["EnterDecryptionPassword"] = "Introduce la contraseña de descifrado:",
        ["ExportFailed"] = "Error al exportar.",
        ["ErrorTitle"] = "Error",
        ["InvalidFile"] = "Archivo no válido o contraseña incorrecta.",
        ["ImportSuccess"] = "Ajustes importados correctamente.",
        ["ImportTitle"] = "Importar",
        ["ImportFailed"] = "Error al importar. Comprueba la contraseña.",
        ["FillEmailFields"] = "Rellena todos los campos de correo (servidor, puerto, usuario, contraseña, de, para).",
        ["TestEmailTitle"] = "Correo de prueba",
        ["TestEmailSent"] = "¡Correo de prueba enviado correctamente!",
        ["TestEmailFailed"] = "No se pudo enviar el correo de prueba:\n{0}",
        ["FillTelegram"] = "Rellena el token del bot y el ID de chat.",
        ["TestTelegramTitle"] = "Probar Telegram",
        ["TestTelegramSent"] = "¡Mensaje de prueba enviado a Telegram correctamente!",
        ["TestTelegramFailed"] = "No se pudo enviar el mensaje de prueba de Telegram:\n{0}",
        ["BatchInputTitle"] = "Entrada por lote",
        ["BatchInputHeader"] = "✎  Entrada por lote",
        ["EnterHosts"] = "Introduce nombres de host o IPs (uno por línea):",
        ["FormatHint"] = "Formato: nombre de host o IP:puerto (p. ej. 192.168.1.1:80)",
        ["AddAll"] = "Añadir todo",
        ["PasswordTitle"] = "Contraseña",
        ["Ok"] = "Aceptar",
        ["AlertsHeader"] = "⬟ Alertas",
        ["AlertsWindowTitle"] = "Alertas de IpScope",

        ["EmailTimestamp"] = "Fecha",
        ["TestEmailSubject"] = "[IpScope Pro] Correo de prueba",
        ["TestEmailBody"] = "Este es un correo de prueba de IpScope Pro.\nSi lo has recibido, la configuración de notificaciones por correo es correcta.",
        ["TestTelegramMessage"] = "Este es un mensaje de prueba de IpScope Pro.\nSi lo has recibido, la configuración de notificaciones de Telegram es correcta."
    };
}
